name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: '22'

      - name: yarn install
        uses: backstage/actions/yarn-install@2cd6978b476cbdc39fec48346f8b6ca13199dd6a # v0.7.8
        with:
          cache-prefix: ${{ runner.os }}-v22

      - name: Run test and build
        run: |
          yarn test:all:no-watch
          yarn tsc
          yarn build:all
