name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '22'

      - name: yarn install
        uses: backstage/actions/yarn-install@0d281eb2e96927466db49d4cd01d52b14809a66b # v0.7.10
        with:
          cache-prefix: ${{ runner.os }}-v22

      - name: Run test and build
        run: |
          yarn test:all:no-watch
          yarn tsc
          yarn build:all
