name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org' # Needed for auth
          package-manager-cache: false

      - name: yarn install
        uses: backstage/actions/yarn-install@a9e1b58ad52aaf319264e18c3ff6887a4c824b52 # v0.7.13
        with:
          cache-prefix: ${{ runner.os }}-v22

      - name: Compile TypeScript
        run: yarn tsc

      - name: Build all packages
        run: yarn build:all

      - name: Publish
        id: changesets
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51
        with:
          version-script: node .github/changeset-version.cjs
          publish-script: yarn publish
          github-token: ${{ secrets.GITHUB_TOKEN }}
